<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Dev;Live</Configurations>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Dev|AnyCPU'">
		<OutputPath>..\Publish\bin\Sync\Dev</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Live|AnyCPU'">
		<OutputPath>..\Publish\bin\Sync\Live</OutputPath>
	</PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="Codev.Core.Common" Version="8.0.5" />
    <PackageReference Include="NodaTime" Version="3.1.11" />
  </ItemGroup>

</Project>
