<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Configurations>Dev;Live</Configurations>
    <Nullable>disable</Nullable>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Dev|AnyCPU'">
		<OutputPath>..\Publish\bin\Sync\Dev</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Live|AnyCPU'">
		<OutputPath>..\Publish\bin\Sync\Live</OutputPath>
	</PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="Codev.Core" Version="9.0.5" />
    <PackageReference Include="NodaTime" Version="3.2.2" />
  </ItemGroup>

</Project>
