<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Configurations>Dev;Live</Configurations>
    <Nullable>disable</Nullable>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Dev|AnyCPU'">
	  <OutputPath>..\Publish\bin\Dev</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Live|AnyCPU'">
	  <OutputPath>..\Publish\bin\Live</OutputPath>
	</PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="Codev.Core" Version="9.3.6" />
    <PackageReference Include="NodaTime" Version="3.3.4" />
  </ItemGroup>

</Project>
